export const BASED_URL="http://127.0.0.1/";
export const time=""
export const api="/api";
export const MIN_NAME_LENGTH=1;
export const MAX_NAME_LENGTH=8;
export const MIN_PWD_LENGTH=8;
export const MAX_PWD_LENGTH=16;
export const MIN_LOADING_TIME=2500;
export const LOADING_STRING=["로딩 중입니다.기다려주세요.","오래 걸리지는 않을 겁니다...","저는 고양이를 키웁니다. 이름은 콩이에요.","오늘의 항해는 어떠셨나요?","오늘도 수고하셨습니다."]
export const DOMAIN="52.78.25.14";