# Generated by Django 3.2.7 on 2021-11-19 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='voyager_name',
            field=models.CharField(default='익명의 항해자', help_text='1~8자 사이로 입력해 주세요.', max_length=8, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='200자 이내로 입력해 주세요.', max_length=200, unique=True),
        ),
    ]
